#!/bin/sh

# Enable key repeat on OS X Lion and after
defaults write -g ApplePressAndHoldEnabled -bool false

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -boolean YES

# Hide desktop icons
defaults write com.apple.finder CreateDesktop false

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Show all filename extensions in Finder
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Show status bar in Finder
defaults write com.apple.finder ShowStatusBar -bool true

# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

# Kill affected applications
for app in Finder Dock SystemUIServer; do killall "$app" > /dev/null 2>&1; done
echo "OSX Hacks Done. Note that some of these changes require a logout/restart to take effect."
